
translate = {
    "en_GB": {
	"title": "Discover what my genes do!",
	"High Scores": "High scores",
	"Show rules": "Show rules",
	"Hide rules": "Hide rules",
	"Make population": "Make population",
	"Hide population": "Hide population",
	"New game": "New game",
	"if gene": "if gene",
	"is": "is",
	"then": "then creature has",
	"pink": "pink",
	"blue": "blue",
	"yellow": "yellow",
	"red": "red",
	"body": "body",
	"head": "head",
	"eyes": "eyes",
	"legs": "legs",
	"Guess": "Guess the rules that made this population:",
	"seconds left": " seconds left!", 
	"Out of time": "Out of time!", 
	"Clear scores": "Clear high score table",
	"You scored": "You scored ",
	"Enter name": "! To go in the high score table enter your name.", 
	"": ""
    },
    "cy": {
	"title": "Dewch i ddarganfod beth mae fy ngenynnau yn ei wneud!",
	"High Scores": "Sgorau uchel",
	"Show rules": "Dangos rheolau",
	"Hide rules": "Cuddion rheolau",
	"Make population": "Creu poblogaeth",
	"Hide population": "Cuddio poblogaeth",
	"New game": "Gêm newydd", 
	"if gene": "os yw genyn",
	"is": "yn",
	"then": "yna fydd greadur yn",
	"pink": "pinc",
	"blue": "glas",
	"yellow": "melyn",
	"red": "coch",
	"body": "corff",
	"head": "pen",
	"eyes": "llygaid",
	"legs": "coesau",
	"Guess": "Dyfalwch y rheolau a wnaeth y boblogaeth hon:",
	"seconds left": " eiliad ar ôl!",
	"Out of time": "Allan o amser!",
	"Clear scores": "Clir bwrdd sgorau uchel", 
	"You scored": "Rydych chi wedi sgorio ",
	"Enter name": "! I fynd yn y tabl sgorau uchel rhowch eich enw.",
	"": ""
    }
};

//  gene 1 is 0 then creature has {pink/blue/yellow/red} {body/legs/eyes/head}, os yw genyn 1 yn 0 yna fydd greadur yn {pinc / / melyn / coch glas} {corff / coesau / llygaid / pen}